### ISSUE TITLE
Why a new VSCode extension?

### ISSUE THREAD

**Issue by JounQin** [jinxdash/prettier-plugin-rust#1]
Doesn't this plugin work perfectly with the official one?

**Comment by jinxdash** [comment]
How'd you install a prettier plugin in a rust project?

**Comment by JounQin** [comment]
> How'd you install a prettier plugin in a rust project?

`npm i -g prettier prettier-plugin-rust`

**Comment by jinxdash** [comment]
How do you update the plugin when there's a new version?

**Comment by JounQin** [comment]
> How do you update the plugin when there's a new version?

`npm upgrade -g prettier-plugin-rust`

**Comment by JounQin** [comment]
There are a lot of prettier plugins supporting other languages, we don't need/want one prettier plugin requires a new VSCode extension. 😂

**Comment by jinxdash** [comment]
> > How do you update the plugin when there's a new version?
>
> `npm upgrade -g prettier-plugin-rust`

Right, so let's keep in mind that the rust userbase is not necessarily familiar with npm, and is unlikely to even have the core extension to begin with. A standalone extension makes the installation easier for everyone, and has auto-updates built-in

> [...] plugin requires a new VSCode extension. 😂

Nobody's requiring anything, you're free to use the plugin however you see fit

**Comment by JounQin** [comment]
> Installing the standalone extension is not required, you're free to use the plugin however you see fit

I know the extension is not required, but as I mentioned above, a new extension for every prettier language plugin is just confusing and unexpected IMO.

I don't see VSCode extensions for `@prettier/plugin-ruby` or `prettier-plugin-java` for example.

`prettier` **is** a node module, so whoever wants to use it should already know about that.

A new extension for every prettier language prettier is a bad practice, sorry I may be rude here.
