### ISSUE TITLE
Insert extra symbol, error occurs.

### ISSUE THREAD

**Issue by Chanyon** [jinxdash/prettier-plugin-rust#11]
### Input code

```rust
KeyEvent {
                code: code @ (KeyCode::Up | KeyCode::Down | KeyCode::Left | KeyCode::Right | KeyCode::End | KeyCode::Home),
                modifiers: event::KeyModifiers::NONE,
            } => {
                self.output.move_cursor(code);
            }
```

### Output code

```rust
KeyEvent {
                code: code @ (
                    | KeyCode::Up
                    | KeyCode::Down
                    | KeyCode::Left
                    | KeyCode::Right
                    | KeyCode::End
                    | KeyCode::Home
                ),
                modifiers: event::KeyModifiers::NONE,
            } => {
                self.output.move_cursor(code);
            }
```

### Additional context

 Insert extra symbols after format.

![bug](https://user-images.githubusercontent.com/40350332/186160934-53b661e2-3b21-45a3-a8d4-5530d73cdc6a.PNG)
.

**Comment by jinxdash** [comment]
It looks like `rust-analyzer`'s custom parser does not support leading `|` in patterns. I filed an issue [here](https://github.com/rust-lang/rust-analyzer/issues/13094).
In the meantime I recommend removing the leading `|` and ignoring that code by placing `// prettier-ignore` above it.

**Comment by jinxdash** [comment]
This issue has been [fixed in `rust-analyzer`](https://github.com/rust-lang/rust-analyzer/pull/13096). 
From what I understand the fix should be part of next week's release, or tomorrow if you use rust-analyzer nightly.
